/* autogenerated by Processing revision 1277 on 2022-01-12 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class image_captcha_code extends PApplet {


int no_of_images = 50;

 public void setup(){

  /* size commented out by preprocessor */;
  /* smooth commented out by preprocessor */;

  String timeNow = year() +""+month() + "" + day() + "_" +hour() + "" +minute() + ""+ second();
  generate(timeNow, no_of_images);
  
  
}


 public void generate(String folder, int count){
  
  JSONArray json = new JSONArray();
  
  for (int x = 0; x < count; x++){
    background(255);  // background color
    fill(0);          // text color
    JSONObject j = new JSONObject();
    String k = str(PApplet.parseInt(random(1000, 10000)));
    String v = str(PApplet.parseInt(random(1000, 10000)));
    
    File f = dataFile("generated/" + folder + "/" + k +".jpg");
    boolean exist = f.isFile();

    if (exist){
      --x;
      continue;
    }
    j.setString(k, v);
    json.setJSONObject(x, j);
    textAlign(CENTER, CENTER);
    textSize(60);
    text(v, 150, 150);
    save("generated/" + folder + "/" + k +".jpg");
  }
  saveJSONArray(json, "generated/" + folder + "/mapping.json");
  exit(); 
}


  public void settings() { size(300, 300);
smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "image_captcha_code" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
